### ISSUE TITLE
Unified query doesn't work with jdbc connection

### ISSUE THREAD

**Issue by amalieiev** [yaroslav-kovalchyk/tamanoir#1]
Unified query doesn't work with jdbc connection.
Try to send post request to http://{serviceHost}/rest/connections/{connectionId}

with headers
Accept: 'application/json'
Content-Type: 'application/json'

with body
body: {"limint": 5}

result: 
{
    "message": "Unexpected exception occurs: java.lang.NullPointerException:null",
    "code": "unexpected.error"
}

**Comment by yaroslav-kovalchyk** [comment]
Fixed. Should work now
