### ISSUE TITLE
There are no relations in metadata for Foodmart database

### ISSUE THREAD

**Issue by amalieiev** [yaroslav-kovalchyk/tamanoir#2]
There are no relations in metadata for Foodmart database.
Try to send POST request to http://{serviceHost}/rest/connections?expand=public.account

with headers
Accept: 'application/metadata+json'
Content-Type: 'application/json'

with body
{
  "type": "jdbc",
    "url":"jdbc:postgresql://localhost:5432/foodmart",
  "properties":{"user":"postgres","password":"PASSWORD"}
}

actual result
only column name and database type present in result

**Comment by yaroslav-kovalchyk** [comment]
Foodmart DB doesn't have any constraint, that's why tamanoir can't detect whether column is identifier or reference.
