### ISSUE TITLE
Database types instead of Java types

### ISSUE THREAD

**Issue by amalieiev** [yaroslav-kovalchyk/tamanoir#3]
Database types instead of Java types present in result.
Try to send POST request to http://{serviceHost}/rest/connections?expand=public.account

with headers
Accept: 'application/metadata+json'
Content-Type: 'application/json'

with body
{
  "type": "jdbc",
    "url":"jdbc:postgresql://localhost:5432/foodmart",
  "properties":{"user":"postgres","password":"PASSWORD"}
}

actual result
Database types instead of Java types present in result.

**Comment by yaroslav-kovalchyk** [comment]
Fixed. Should work now.
