### ISSUE TITLE
Direct node metadata

### ISSUE THREAD

**Issue by amalieiev** [yaroslav-kovalchyk/tamanoir#4]
Is it possible to get metadata for one node, not all tree?
For example when I send metadata request to 'public.user' I expect data like
[
{name: id, type: 'integer'},
{name: name, type: 'string'},
{name: salaryid, type: 'integer', referenceTo: 'public.salaries.id'}
]

**Comment by yaroslav-kovalchyk** [comment]
Implemented. Use like this: include=public.jiresource
